### ISSUE TITLE
Cannot join Cromemco group on Google

### ISSUE THREAD

**Issue by jok2000** [cromemcos/public#2]
My name is Jeff Kesner, I will be using jok@ca.inter.net on github.   We owned a Cromemco Z-2 around about 1978-1979 (alas, recycled in 1998)   I refamiliarized myself with the system when I got an earlier version of your Cromemco emulator last year.  Also this means I have a valid license to use the various software like the Fortran compiler, documentation and whatnot.

Could you grant me access to the Cromemco group on Google?

**Comment by kazueda** [comment]
Me too.
I am a 8 bit CPU lover and I found that Cromemco Z-1 had Z80 CPU.
I cannnot obtain a real hardware but I use a cromemco emulator.
Please add my github e-mail address to subscriber's list.

**Comment by cromemcos** [comment]
Dear Kazueda.  A warm welcome.    I am sending you a private email with the process which is basically

a) join the Cromemco Google Group

b) Read the terms for the private Github here https://github.com/cromemcos/public

this is the important bit

Explicitly agree by reply of email to [cromemcos@gmail.com](mailto:cromemcos@gmail.com) to the following terms. Don't forget to quote the text here in your reply.

**Comment by kazueda** [comment]
Thank you for your e-mail.
I heard from udo munk that the administrator of Cromemco Google Group has
not added any new members to the group anymore.
 Mr Marcus is the only person who can add a new member to the group.

I want to join the group.
How can I join the group?
Sincerely yours,
Kazumasa Ueda

2022年12月20日(火) 20:10 cromemco ***@***.***>:

**Comment by kazueda** [comment]
Sorry for my confusion.
After sending you my e-mail, I noticed I was added to the group.
Thank you for your kindness.





2022年12月20日(火) 20:24 Kazumasa Ueda ***@***.***>:
